### ISSUE TITLE
Add new title

### ISSUE THREAD

**Issue by YibinWu** [Koohoko/Koohoko.github.io#5]
Hi, 请问您在主页上新建一个标题，比如CV后，除了在navigation.yml添加关于cv的link之外，还需要修改什么地方吗？我修改navigation.yml后，点击网页顶部新建的标签，并不会导航到主页对应的部分而是刷新网页，谢谢。

**Comment by Koohoko** [comment]
> Hi, 请问您在主页上新建一个标题，比如CV后，除了在navigation.yml添加关于cv的link之外，还需要修改什么地方吗？我修改navigation.yml后，点击网页顶部新建的标签，并不会导航到主页对应的部分而是刷新网页，谢谢。

Hi, 你还需要在你的主页html里面添加锚点, 参见https://github.com/Koohoko/Koohoko.github.io/blob/4c4e692e60c049a11f9da2b6344a98516370fac6/_pages/about.md?plain=1#L20。或用一级标题作为锚点。

**Comment by Koohoko** [comment]
> Hi, 请问您在主页上新建一个标题，比如CV后，除了在navigation.yml添加关于cv的link之外，还需要修改什么地方吗？我修改navigation.yml后，点击网页顶部新建的标签，并不会导航到主页对应的部分而是刷新网页，谢谢。

另外我看了一下，你navigation.yml的格式可能不对，请参考https://github.com/Koohoko/Koohoko.github.io/blob/4c4e692e60c049a11f9da2b6344a98516370fac6/_data/navigation.yml#L13

**Comment by YibinWu** [comment]
您好，谢谢回复。我在about.md里面已经添加了这个锚点，也在navigation.yml里面改了标签的格式，但还是有问题。点击上端导航栏的academic service不会定位到页面上对应的位置。
`<span class="anchor" id="about-me"></span> `
`  - title: "Academic Services"
    url: "/#academic-services"`

**Comment by Koohoko** [comment]
> 您好，谢谢回复。我在about.md里面已经添加了这个锚点，也在navigation.yml里面改了标签的格式，但还是有问题。点击上端导航栏的academic service不会定位到页面上对应的位置。
> `<span class="anchor" id="about-me"></span> `
> ` - title: "Academic Services" url: "/#academic-services"

https://github.com/YibinWu/yibinwu.github.io/blob/3c9f5ef0836788391dbdca4985e8ad09a4a51924/_data/navigation.yml#L25

试一下把"/#academic-services"改成"/#-academic-services"？

另外如果你用一集标题作为锚点的话，anchor那个class就不需要了。

**Comment by YibinWu** [comment]
hi您好。我把"/#academic-services"改成"/#-academic-services"之后还是不行，试着把`<span class="anchor" id="about-me"></span>`这个删掉后点击About me也变成了重新加载页面。最后试着在about.md Academic Services标题处加了`<span class='anchor' id='-academic-services'></span>`，问题解决了。但是看您加了一个CV的标题，没有手动指定这个锚点也可以在点击导航栏后实现页面定位，好奇您是怎么做到的。谢谢。

**Comment by Koohoko** [comment]
> hi您好。我把"/#academic-services"改成"/#-academic-services"之后还是不行，试着把`<span class="anchor" id="about-me"></span>`这个删掉后点击About me也变成了重新加载页面。最后试着在about.md Academic Services标题处加了`<span class='anchor' id='-academic-services'></span>`，问题解决了。但是看您加了一个CV的标题，没有手动指定这个锚点也可以在点击导航栏后实现页面定位，好奇您是怎么做到的。谢谢。

我的理解是其实在html页面内跳转，只要有id就可以，你看我的主页的html源文件会发现，cv那里是
<h1 id="cv"><a href="("/files/CV/CV_haogao.pdf")">CV</a></h1>
有cv这个id就可以用网址后面加“#cv”来跳转了。
具体你可以搜一下“html页面内跳转”看看

**Comment by YibinWu** [comment]
Soga，谢谢！
